//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dish
    {
        public int Id { get; set; }
        public int RestaurantId { get; set; }
        public Nullable<int> CuisineId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Flavors { get; set; }
        public string Ingredients { get; set; }
        public string Category { get; set; }
        public double Price { get; set; }
        public string Image { get; set; }
        public bool Deleted { get; set; }
        public string CloverId { get; set; }
    }
}
