//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dish
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dish()
        {
            this.OrderedDishes = new HashSet<OrderedDish>();
        }
    
        public int Id { get; set; }
        public int RestaurantId { get; set; }
        public Nullable<int> CuisineId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Flavors { get; set; }
        public string Ingredients { get; set; }
        public string Category { get; set; }
        public double Price { get; set; }
        public string Image { get; set; }
    
        public virtual Cuisine Cuisine { get; set; }
        public virtual Restaurant Restaurant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderedDish> OrderedDishes { get; set; }
    }
}
