
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class Payment
{

    public int Id { get; set; }

    public bool Success { get; set; }

    public System.DateTime CreationDate { get; set; }

    public string UserId { get; set; }

    public string TransactionId { get; set; }

    public string OrderId { get; set; }

}

}
