//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Preference
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public string Ingredients { get; set; }
        public Nullable<int> CuisineId { get; set; }
        public string Dishes { get; set; }
        public string Flavors { get; set; }
        public int Count { get; set; }
    }
}
